include:
  - .docker/nestjs-monorepo/docker-compose.yml

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
