services:
  api.application-openings:
    image: application-openings:latest
    build: ../
    env_file: ./../../../.env
    container_name: api.application-openings
    environment:
      - VIRTUAL_HOST=api.application-openings.localhost
    volumes:
      - ./../../../projects/go-basic/:/app
    #command: sh -c "go run main.go"
    depends_on:
      - nginx-proxy
      - db.mysql.application-openings

  db.mysql.application-openings:
    image: mysql:latest
    container_name: db.mysql.application-openings
    environment:
      MYSQL_USER: ${APPLICATION_OPENINGS__DB_USER}
      MYSQL_PASSWORD: ${APPLICATION_OPENINGS__DB_PASS}
      MYSQL_DATABASE: ${APPLICATION_OPENINGS__DB_NAME}
      MYSQL_ROOT_PASSWORD: ${APPLICATION_OPENINGS__DB_PASS}
    volumes:
      - db.mysql.application-openings:/data/db
    ports:
      - 3306:3306
    restart: always

volumes:
  db.mysql.application-openings:
