services:
  api.application-template:
    image: application-template:latest
    build: ../
    env_file: ./../../../.env
    container_name: api.application-template
    environment:
      - VIRTUAL_HOST=api.application-template.localhost
    volumes:
      - ./../../../projects/nestjs-monorepo/:/app
    command: sh -c "npm i --ignore-scripts && npm run start:dev -- application-template"
    depends_on:
      - nginx-proxy
      - db.mongo.application-template

  db.mongo.application-template:
    image: mongo:latest
    container_name: db.mongo.application-template
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APPLICATION_TEMPLATE__DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${APPLICATION_TEMPLATE__DB_PASS}
      MONGO_INITDB_DATABASE: ${APPLICATION_TEMPLATE__DB_NAME}
    volumes:
      - db.mongo.application-template:/data/db
    ports:
      - 27017:27017
    restart: always

volumes:
  db.mongo.application-template:
